# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [11]:
import numpy as np
from scipy import stats

In [43]:
#Creating sample array
arr = np.array([1,2,3,4,5,6,7,8,9,10])

#Show
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
# print(stats.describe(arr))
print("variance:", stats.describe(arr).variance)
print("skewness:", stats.describe(arr).skewness)

variance: 9.166666666666666
skewness: 0.0


## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [34]:
#Get a value at an index

arr[8]

9

In [35]:
#Get values in a range
print(arr[1:5])

array([2, 3, 4, 5])

In [36]:
#Get values in a range
arr[0:5]

array([1, 2, 3, 4, 5])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [42]:
print(arr)

[100 100 100 100 100   6   7   8   9  10]


In [50]:
#Setting a value with index range (Broadcasting)
arr[0:5] = 100
print(arr)

[100 100 100 100 100   6   7   8   9  10]


In [56]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [57]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
print(slice_of_arr)

[0 1 2 3 4 5]


In [58]:
#Change Slice
slice_of_arr[:] = 99

#Show Slice again
print(slice_of_arr)

[99 99 99 99 99 99]


Now note the changes also occur in our original array!

In [59]:
print(arr)

[99 99 99 99 99 99  6  7  8  9 10]


Data is not copied, it's a view of the original array! This avoids memory problems!

In [60]:
#To get a copy, we need to be explicit!
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [61]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
print(arr_2d)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [63]:
#Indexing row
print(arr_2d[1])


[20 25 30]


In [64]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [65]:
# Getting individual element value
arr_2d[1,0]

20

In [74]:
# 2D array slicing

#Shape (2,2) from top right corner
print(arr_2d[ 1:, :2])

[[20 25]
 [35 40]]


In [ ]:
#Shape bottom row
arr_2d[2]

In [ ]:
#Shape bottom row
arr_2d[2,:]

In [ ]:
arr_2d

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [75]:
#Set up matrix
arr2d = np.zeros((10,10))
print(arr2d)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [76]:
#Length of array
print("Row x Col:", arr2d.shape)

arr_length = arr2d.shape[1]
print("length:", arr_length)

Row x Col: (10, 10)
length: 10


In [77]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [87]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
print(arr > 4)

[False False False False  True  True  True  True  True  True]


In [90]:
bool_arr = arr>4

In [91]:
print(bool_arr)

[False False False False  True  True  True  True  True  True]


In [98]:
cond = np.logical_or(arr > 4, arr < 2)
print(cond)

[ True False False False  True  True  True  True  True  True]


In [99]:
arr[cond]

array([ 1,  5,  6,  7,  8,  9, 10])

In [113]:
cond = arr < 5
print(cond)

print(arr[np.logical_not(cond)])


[ True  True  True  True False False False False False False]
[ 5  6  7  8  9 10]


# Great Job!
